#!/bin/bash

stow=`which stow`
stow_root=`dirname $0`
stow_pkgs=`find ${stow_root} -type d -depth 1 -not -name ".*" -exec basename {} \;`

pushd ${stow_root}
for pkg in ${stow_pkgs}; do
  ${stow} ${pkg}
done
popd
